name: venera
description: "A comic app."
publish_to: 'none'

version: 1.4.2+142

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  intl: any
  window_manager: ^0.4.3
  sqlite3: ^2.7.4
  sqlite3_flutter_libs: ^0.5.30
  flutter_qjs:
    path: pubdependencies/flutter_qjs
  crypto: ^3.0.6
  dio: ^5.8.0+1
  html: ^0.15.5
  pointycastle: ^4.0.0
  url_launcher: ^6.3.0
  path: ^1.9.0
  photo_view:
    path: pubdependencies/photo_view
  mime: ^2.0.0
  share_plus: ^10.1.4
  scrollable_positioned_list:
    path: pubdependencies/flutter.widgets/packages/scrollable_positioned_list
  flutter_reorderable_grid_view: ^5.4.0
  uuid: ^4.5.1
  desktop_webview_window:
    path: pubdependencies/flutter_desktop_webview/packages/desktop_webview_window
  flutter_inappwebview:
    path: pubdependencies/flutter_inappwebview/flutter_inappwebview
  app_links: ^6.4.0
  sliver_tools: ^0.2.12
  flutter_file_dialog: ^3.0.2
  file_selector: ^1.0.3
  zip_flutter: ^0.0.12
  lodepng_flutter:
    path: pubdependencies/lodepng_flutter
  rhttp:
    path: pubdependencies/rhttp/rhttp
  webdav_client:
    path: pubdependencies/webdav_client
  battery_plus: ^6.2.1
  local_auth: ^2.3.0
  flutter_saf:
    path: pubdependencies/flutter_saf
  dynamic_color: ^1.7.0
  shimmer_animation: ^2.1.0
  flutter_memory_info: ^0.0.1
  syntax_highlight: ^0.4.0
  flutter_7zip:
    path: pubdependencies/flutter_7zip
  flex_seed_scheme: ^3.5.0
  flutter_localizations:
    sdk: flutter
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_to_arch: ^1.0.1
  flutter_to_debian: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/translation.json
    - assets/init.js
    - assets/app_icon.png
    - assets/tags.json
    - assets/tags_tw.json

flutter_to_arch:
  name: Venera
  icon: debian/gui/venera.png
  categories: Utility
  keywords: Flutter;comic;images;
  url: https://github.com/venera-app/venera
  depends:
    - gtk3
    - webkit2gtk-4.1
